# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FT-Coding-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FT-Coding-Test

  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'ReachabilitySwift'
  pod 'MBProgressHUD', '~> 1.1.0'

  target 'FT-Coding-TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FT-Coding-TestUITests' do
    # Pods for testing
  end

end
